### ISSUE TITLE
When is the framework expected to be ready for use and can you write a document on how to use it?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ducdetronquito/express#35]

**Comment by ducdetronquito** [comment]
Hi @Yakumo-Yukari,

The framework is a personnal project of mine so I cannot give you any deadline.

If you are looking for more stable web framework for Nim, you should reach for [prologue](https://github.com/planety/prologue) or [jester](https://github.com/dom96/jester).

But if you want to give it a try, I would be really gratefull for your feedbacks :)
